# Generated by Django 4.0.6 on 2022-07-06 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('price', models.IntegerField()),
                ('short_description', models.CharField(max_length=500)),
                ('desc', models.TextField()),
                ('ia', models.BooleanField(default=False, null=True, verbose_name="is/isn't active")),
                ('is_deleted', models.BooleanField(default=False, null=True, verbose_name="is/isn't deleted")),
                ('slug', models.SlugField(blank=True, default='', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Category Name')),
                ('url_title', models.CharField(db_index=True, max_length=150, verbose_name='Category Name in url')),
                ('ia', models.BinaryField(verbose_name="Is/ ISn't Active")),
                ('is_deleted', models.BooleanField(default=False, null=True, verbose_name="is/isn't deleted")),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_tags', to='product.product')),
            ],
            options={
                'verbose_name': 'product tag',
                'verbose_name_plural': 'product tags',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='Product_Categories', to='product.productcategory'),
        ),
    ]
