# Generated by Django 4.0.6 on 2022-07-11 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productbrand_product_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbrand',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
    ]
