# Generated by Django 4.0.5 on 2022-07-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productcategory_alter_product_slug_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='url_title',
            field=models.CharField(max_length=150, verbose_name='Category Name in url'),
        ),
    ]
